### ISSUE TITLE
ln failed to create link, operation not permitted

### ISSUE THREAD

**Issue by nclowell** [enormandeau/stacks_workflow#34]
I'm getting the following error when running ``03_rename_samples.sh``:

``ln: failed to create hard link: '04-all_samples/YakutatBayAK_58320-E3-300NG.fq.gz' => '03-samples/PARCAL_RUN4_1/sample_GGGGCG.fq.gz': Operation not permitted``

Sounds like a permission issue. I tried running the script with sudo, and also made a copy of the script where I add sudo to the ln call. Neither worked. Any ideas?

Thanks for putting together this workflow! Super helpful!

**Comment by enormandeau** [comment]
Hi. It does sound like a permission issue. Maybe try this on the stacks_workflow directory:

```bash
chmod -R u=rwX stacks_workflow
```

Tell me how it goes.

**Comment by nclowell** [comment]
Thanks for the suggestion! Unfortunately it didn't work. 

It might be worth mentioning that I'm working within a linux virtual machine, and the stacks_workflow directory is on a shared drive that I do have read and write access to from the vm:

``vmhgfs-fuse on /mnt/hgfs type fuse.vmhgfs-fuse (rw,nosuid,nodev,allow_other)``

**Comment by enormandeau** [comment]
Ah, you cannot do soft links (with either `ln` or `cp -l`) from a drive to another, although probably the 03 and 04 folders are on the same drive...

If your dataset isn't too big, I would consider replacing `ln` in the script with `cp`. The goal of the soft links is to save the disk space and time needed to do the copy.

This is totally unrelated, but I see you may have worked on sea cucumbers. Do you know Amanda Xuereb? We used stacks_workflow on her see cuke GBS a while back :)

**Comment by nclowell** [comment]
Indeed, both the 03 and 04 dirs are on the same drive. Regardless, I'll try cp or figure out a work around in python for renaming and moving. The goal is just to have files in the new directory, with names population_identifier.fq.gz, correct, with fastqs concatenated if there are replicate files with the same name?

Is ln used in any other script downstream?

And thank again for your help! Amanda pointed me to your workflow :) I've tried ipyrad and dDocent and had some issues with marine inverts being quite diverse, and am now giving Stacks a try!

**Comment by enormandeau** [comment]
That is correct, you only want the files in 03 to be in 04 with a sample name that is useful to you. The reason for the complexity of this script is that you may have **multiple files** for the same sample in the 03 folder if you ran them on multiple chips / lanes, for example.

**Note** that the sample names MUST have the following format: `POP_SAMPLE`, where POP is a population name that does **not** contain underscores (`_`) and SAMPLE is a sample name, with no underscores also.

`ln` isn't used after that script.

Are you using STACKS 2.4 with a reference genome ?

stacks_workflow is evolving fast right now because I am running a full analysis plus filters on new STACKS 2.4 datasets. It may be good to stay up to date for both the documentation (read it online on the repository page) but also the filtering scripts. Lets say that if you use STACKS 2.4, once you have a `population.snps.vcf`, you should use the newest version of stacks_workflow **and** read the up-to-date documentation as you do the filtration.

**Comment by nclowell** [comment]
Yes - Stacks 2.4 with a genome!

I'll follow your repo - thanks for the heads-up.

Thanks!

**Comment by enormandeau** [comment]
Marking as closed. Feel free to re-open or open another issue for another problem.

**Comment by Anteino** [comment]
> Ah, you cannot do soft links (with either `ln` or `cp -l`) from a drive to another, although probably the 03 and 04 folders are on the same drive...

This saved me a lot of time, thanks!
